enum EVENT_ID {
	// joystick events
	EVENT_INPUT_SW1,
	EVENT_INPUT_SW2,
	EVENT_INPUT_SW3,
	EVENT_INPUT_SW4,
	EVENT_INPUT_SW5,
	EVENT_INPUT_SW6,
	EVENT_INPUT_TGL1_ON,
	EVENT_INPUT_TGL1_OFF,
	EVENT_INPUT_TGL2_ON,
	EVENT_INPUT_TGL2_OFF,
	EVENT_INPUT_TGL3_ON,
	EVENT_INPUT_TGL3_OFF,
	EVENT_INPUT_TGL4_ON,
	EVENT_INPUT_TGL4_OFF,
	EVENT_INPUT_MODE_SW,

	// PMDG NGX events
	EVENT_HEADING_SELECTOR,
	EVENT_SPEED_SELECTOR,
	EVENT_ALTITUDE_SELECTOR,
	EVENT_COURSE_SELECTOR_L,
	EVENT_COURSE_SELECTOR_R,
	EVENT_BARO_SELECTOR_L,
	EVENT_MINS_SELECTOR_L,

	// FSX radio tune events
	EVENT_NAV1_RADIO_WHOLE_DEC,
	EVENT_NAV1_RADIO_WHOLE_INC,
	EVENT_NAV1_RADIO_FRACT_DEC,
	EVENT_NAV1_RADIO_FRACT_INC,
	EVENT_NAV1_RADIO_SWAP,
	EVENT_NAV2_RADIO_WHOLE_DEC,
	EVENT_NAV2_RADIO_WHOLE_INC,
	EVENT_NAV2_RADIO_FRACT_DEC,
	EVENT_NAV2_RADIO_FRACT_INC,
	EVENT_NAV2_RADIO_SWAP,
	EVENT_COM1_RADIO_WHOLE_DEC,
	EVENT_COM1_RADIO_WHOLE_INC,
	EVENT_COM1_RADIO_FRACT_DEC,
	EVENT_COM1_RADIO_FRACT_INC,
	EVENT_COM1_RADIO_SWAP,
	EVENT_COM2_RADIO_WHOLE_DEC,
	EVENT_COM2_RADIO_WHOLE_INC,
	EVENT_COM2_RADIO_FRACT_DEC,
	EVENT_COM2_RADIO_FRACT_INC,
	EVENT_COM2_RADIO_SWAP,
	EVENT_ADF1_RADIO_WHOLE_DEC,
	EVENT_ADF1_RADIO_WHOLE_INC,
	EVENT_ADF1_RADIO_FRACT_DEC,
	EVENT_ADF1_RADIO_FRACT_INC,
	EVENT_ATC1_RADIO_WHOLE_DEC,
	EVENT_ATC1_RADIO_WHOLE_INC,
	EVENT_ATC1_RADIO_FRACT_DEC,
	EVENT_ATC1_RADIO_FRACT_INC,
};

enum GROUP_ID {
    GROUP_0,
};

void sendLinearIncDecEvent(HANDLE hSimConnect, char value, EVENT_ID inc, EVENT_ID dec) {
	if (value > 0)
		SimConnect_TransmitClientEvent(hSimConnect, 0, inc, 0, SIMCONNECT_GROUP_PRIORITY_HIGHEST, SIMCONNECT_EVENT_FLAG_GROUPID_IS_PRIORITY);

	if (value < 0)
		SimConnect_TransmitClientEvent(hSimConnect, 0, dec, 0, SIMCONNECT_GROUP_PRIORITY_HIGHEST, SIMCONNECT_EVENT_FLAG_GROUPID_IS_PRIORITY);
}

void sendToggleEvent(HANDLE hSimConnect, EVENT_ID evt) {
	SimConnect_TransmitClientEvent(hSimConnect, 0, evt, 0, SIMCONNECT_GROUP_PRIORITY_HIGHEST, SIMCONNECT_EVENT_FLAG_GROUPID_IS_PRIORITY);
}